version: "3.8"

services:
  app:
    container_name: PulumiTest
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ..:/workspace:cached
      - shell-history:/commandhistory
    command: /bin/bash -c "sleep infinity"
    network_mode: "host"

volumes:
  shell-history:
