name: Deploy all services
on:
  push:
    branches:
      - main
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  deploy-s3-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/commands/yarn_install
      - uses: ./.github/commands/aws_login
      - uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: yarn workspace @app/s3-backend exec pulumi up --stack test --yes --refresh

  benchmark-pulumi-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/commands/yarn_install
      - uses: ./.github/commands/aws_login
      - uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: yarn workspace @app/pulumi-backend-test exec pulumi up --stack test --yes --refresh