name: Deploy all services
on:
  push:
    branches:
      - main
  # For testing quickly
  pull_request:
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/commands/yarn_install

      # Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install Pulumi and deploy the infra code
      - uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: yarn workspace @app/s3-backend exec pulumi up --stack test --refresh